[package]
name = "dist-gen"
version = "0.1.0"
authors = ["Walter Pearce <jaynus@gmail.com>"]
edition = "2018"

[dependencies]
flatbuffers = { path = "../flatbuffers/rust/flatbuffers" }
flatc-rust = { path = "../flatc-rust" }
