[package]
name = "dist-macro"
version = "0.1.0"
authors = ["Walter Pearce <jaynus@gmail.com>"]
edition = "2018"

[dependencies]
syn = "*"
quote = "*"
proc-macro2 = "*"

[lib]
proc-macro = true
path = "src/lib.rs"